package exported 
import (
	"fmt"
	"encoding/json"

	"github.com/safing/portbase/log"
	"github.com/safing/portmaster-android/go/engine"
	"github.com/safing/portmaster-android/go/engine/ui"
)


// DO NOT EDIT THIS FILE!
// The file was autogenerated by go/codegenv2/gen.go

func IsTunnelActive(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function IsTunnelActive panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0 := ui.IsTunnelActive()
	
	
	// Resolve the call
	call.ResolveJson(fmt.Sprintf(`{"ret0": %t}`, ret0))
}

func EnableTunnel(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function EnableTunnel panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.EnableTunnel()
	
	
	// Resolve the call
	call.Resolve()
}

func RestartTunnel(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function RestartTunnel panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.RestartTunnel()
	
	
	// Resolve the call
	call.Resolve()
}

func GetLogs(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetLogs panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter ID
	ID, err := call.GetLong("ID")
	if err != nil {
		call.Error("missing ID argument")
		return
	}
	// Function call
	ret0 := ui.GetLogs(ID)
	
	ret0Json, _ := json.Marshal(ret0)
	
	// Resolve the call
	call.ResolveJson(fmt.Sprintf(`{"ret0": %s}`, ret0Json))
}

func GetDebugInfoFile(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetDebugInfoFile panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.GetDebugInfoFile()
	
	
	// Resolve the call
	call.Resolve()
}

func GetDebugInfo(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetDebugInfo panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.GetDebugInfo()
	
	if err1 != nil {
		call.Error(err1.Error())
		return
	}
	
	
	// Resolve the call
	call.ResolveJson(fmt.Sprintf(`{"ret0": "%s"}`, ret0))
}

func Shutdown(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function Shutdown panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.Shutdown()
	
	
	// Resolve the call
	call.Resolve()
}

func CreateIssue(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function CreateIssue panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter debugInfo
	debugInfo, err := call.GetString("debugInfo")
	if err != nil {
		call.Error("missing debugInfo argument")
		return
	}
	// Parameter genUrl
	genUrl, err := call.GetBool("genUrl")
	if err != nil {
		call.Error("missing genUrl argument")
		return
	}
	// Parameter issueRequestStr
	issueRequestStr, err := call.GetString("issueRequestStr")
	if err != nil {
		call.Error("missing issueRequestStr argument")
		return
	}
	// Function call
	ret0, err1 := ui.CreateIssue(debugInfo, genUrl, issueRequestStr)
	
	if err1 != nil {
		call.Error(err1.Error())
		return
	}
	
	
	// Resolve the call
	call.ResolveJson(fmt.Sprintf(`{"ret0": "%s"}`, ret0))
}

func CreateTicket(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function CreateTicket panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter debugInfo
	debugInfo, err := call.GetString("debugInfo")
	if err != nil {
		call.Error("missing debugInfo argument")
		return
	}
	// Parameter ticketRequestStr
	ticketRequestStr, err := call.GetString("ticketRequestStr")
	if err != nil {
		call.Error("missing ticketRequestStr argument")
		return
	}
	// Function call
	err0 := ui.CreateTicket(debugInfo, ticketRequestStr)
	
	if err0 != nil {
		call.Error(err0.Error())
		return
	}
	
	
	// Resolve the call
	call.Resolve()
}

func IsGeoIPDataAvailable(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function IsGeoIPDataAvailable panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.IsGeoIPDataAvailable()
	
	if err1 != nil {
		call.Error(err1.Error())
		return
	}
	
	
	// Resolve the call
	call.ResolveJson(fmt.Sprintf(`{"ret0": %t}`, ret0))
}

func PerformRequest(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function PerformRequest panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	ui.PerformRequest(call)
}

func DatabaseMessage(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function DatabaseMessage panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter msg
	msg, err := call.GetString("msg")
	if err != nil {
		call.Error("missing msg argument")
		return
	}
	// Function call
	ui.DatabaseMessage(msg)
	
	
	// Resolve the call
	call.Resolve()
}

func SubscribeToDatabase(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function SubscribeToDatabase panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	ui.SubscribeToDatabase(call)
}


