package io.safing.portmaster.android.ui;

// DO NOT EDIT THIS FILE!
// The file was autogenerated by io.safing.portmaster.android.codegeneration.GoInterfaceGenerator

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

@CapacitorPlugin(name = "UIBridge")
public class UIBridge extends Plugin {

    @PluginMethod()
    public void isActiveUI(PluginCall call) {
        vpn.Vpn.isActiveUI(new GoPluginCall(call));
    }
}